export const authors = [
  "Eleven",
  "Chloe Decker",
  "Joyce Byers",
  "Jim Hopper",
  "Mike Wheeler",
  "Dustin Henderson",
  "Lucas Sinclair",
  "Jonathan Byers",
  "Max Mayfield",
  "Erica Sinclair",
  "Mr. Clarke",
  "Sam Owens",
  "Kali Prasad",
  "Steve Harrington",
  "Keith",
  "Sam Owens",
  "Nancy Wheeler",
  "Robin Buckley",
  "Florence",
  "Murray Bauman",
  "Will Byers",
  "Bob Newby",
  "Billy Hargrove",
  "Ted Wheeler",
];
